routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Translate with middleware
Route::group(['middleware' => 'localization'], function(){

    Route::get('/', 'Frontend\HomeController@index')->name('welcome');
    Route::get('/search', 'Frontend\HomeController@search')->name('frontend.search');
    Route::get('/search/json', 'Frontend\HomeController@jsonSearch');
    Route::get('change-language', 'Frontend\HomeController@changeLanguage')->name('change-language');

    Route::get('/redirect/{providerName}', 'Frontend\SocialAuthController@redirect')->name('auth.social');
    Route::get('/callback/{providerName}', 'Frontend\SocialAuthController@callback');

    Auth::routes();

    Route::group(['prefix' => 'admin', 'middleware' => 'isAdmin'], function () {
        Route::get('/', 'Admin\AdminController@index');
        Route::match(['get', 'post'], 'setup', 'Admin\AdminController@setup')->name('admin.setup');
        Route::get('json/getStaticstics', 'Admin\AdminController@getStaticstics');

        Route::resource('users', 'Admin\UserController');

        Route::resource('category', 'Admin\CategoryController');
        Route::get('category/{id}/create', 'Admin\CategoryController@subCreate')->name('category.subCreate');

        Route::resource('medicine', 'Admin\MedicineController');

        Route::resource('comment', 'Admin\CommentController');

        Route::resource('rate', 'Admin\RateController');

        Route::resource('request', 'Admin\RequestMedicineController');

        Route::get('orders', 'Admin\OrderController@index')->name('admin.orders.index');
        Route::get('orders/{id}/detail', 'Admin\OrderController@orderDetail')->name('admin.orders.detail');
        Route::put('orders/{id}/detail', 'Admin\OrderController@changeStatus')->name('admin.orders.change');
    });

    Route::group(['middleware' => 'isLogin'], function(){
        // Prescription
        Route::get('/prescription', 'Frontend\PrescriptionController@index')
            ->name('frontend.prescription.index');
        Route::get('/prescription/json/getList', 'Frontend\PrescriptionController@getJsonList');
        Route::delete('/prescription/{id}', 'Frontend\PrescriptionController@destroyPrescription');

        Route::get('/prescription/{id}/edit', 'Frontend\PrescriptionController@editPrescription');
        Route::put('/prescription/{id}/edit', 'Frontend\PrescriptionController@updatePrescription')
            ->name('frontend.prescription.update');

        Route::get('/prescription/addnew', 'Frontend\PrescriptionController@addNewPrescription')
            ->name('frontend.prescription.addnew');
        Route::post('/prescription/addnew', 'Frontend\PrescriptionController@storeNewPrescription')
            ->name('frontend.prescription.store');
        Route::get('/prescription/json/searchMedicines', 'Frontend\PrescriptionController@jsonSeachMedicines');

        // Mark Medicine
        Route::get('/mark-medicine', 'Frontend\HomeController@markMedicineIndex')
            ->name('frontend.mark-medicine.index');
        Route::delete('/mark-medicine/{id}', 'Frontend\HomeController@markMedicineDestroy')
            ->name('frontend.mark-medicine.destroy');

        Route::get('detail/add-to-box', 'Frontend\DetailMedicinesController@addToBox')->name('add_to_box');

        // Add comment
        Route::post('/comment/send/data', 'Frontend\DetailMedicinesController@addEditComment');
        Route::post('/comment/send/data/children', 'Frontend\DetailMedicinesController@addEditChildrenComment');
        Route::post('/comment/delete/children', 'Frontend\DetailMedicinesController@deleteChildrenComment');

        Route::post('/user/edit', 'Frontend\UserProfilesController@editUserInformations')
            ->name('frontend.user.edit.personal');
        Route::post('/user/edit/upload', 'Frontend\UserProfilesController@showUploadAvatar')
            ->name('show_upload_avatar');
        Route::post('/user/change-password', 'Frontend\UserProfilesController@userChangePassword')
            ->name('user_change_password');
        Route::get('/user/profile', 'Frontend\UserProfilesController@index')
            ->name('frontend.user.profiles');


        Route::get('/request-prescription', 'Frontend\RequestPrescriptionController@requestIndex')
            ->name('request-prescription.index');
        Route::get('/request-prescription/add-new', 'Frontend\RequestPrescriptionController@requestAddnew')
            ->name('request-prescription.addnew');
        Route::post('/request-prescription/add-new', 'Frontend\RequestPrescriptionController@requestStore')
            ->name('request-prescription.store');
        Route::get('/request-prescription/json/detail', 'Frontend\RequestPrescriptionController@jsonDetail');
        Route::get('/request-prescription/json/doctorDetail', 'Frontend\RequestPrescriptionController@jsonDoctorDetail');

        Route::get('/request-medicine', 'Frontend\RequestMedicineController@requestIndex')
            ->name('frontend.request-medicine.index');
        Route::get('/request-medicine/add-new', 'Frontend\RequestMedicineController@requestAddnew')
            ->name('frontend.request-medicine.addnew');
        Route::post('/request-medicine/add-new', 'Frontend\RequestMedicineController@requestStore')
            ->name('frontend.request-medicine.store');
        Route::get('/request-medicine/json/detail', 'Frontend\RequestMedicineController@jsonDetail');

        Route::get('/doctor-request-prescription', 'Frontend\RequestPrescriptionController@doctorRequestIndex')
            ->name('doctor-request-prescription.index');
        Route::get('/doctor/{id}/make-prescrition', 'Frontend\PrescriptionController@doctorMakePrescription')
            ->name('frontend.doctor.make-prescription');
        Route::post('/doctor/{id}/make-prescrition', 'Frontend\PrescriptionController@doctorStorePrescription')
            ->name('frontend.doctor.prescription.store');

        Route::get('/convert-prescription/{id}/order', 'Frontend\OrderController@convertToOrder')
            ->name('frontend.convert.order');
        Route::get('checkout', 'Frontend\OrderController@checkout')->name('frontend.checkout');
        Route::post('checkout', 'Frontend\OrderController@checkoutStore')->name('frontend.checkout.store');
        Route::get('order-view/{id}/detail', 'Frontend\OrderController@detailOrder')
            ->name('frontend.order.detail');
        Route::put('order-view/{id}/detail', 'Frontend\OrderController@changeStatus')
            ->name('frontend.order.change');
        Route::get('checkout/success', 'Frontend\OrderController@orderSuccess')
            ->name('frontend.order.success');
        Route::get('user/order-list', 'Frontend\OrderController@orderList')
            ->name('frontend.order.list');
        Route::post('/order/resend/email', 'Frontend\OrderController@resendEmail');
    });

    Route::get('/user/{user_id}/{user_name}', 'Frontend\UserProfilesController@profileDiffUser')
        ->name('frontend.user.different.profiles');

    Route::get('/doctor/list-all', 'Frontend\HomeController@doctorList')->name('frontend.doctor.list');
    Route::get('/doctor/json/getList', 'Frontend\HomeController@jsonDoctorList');

    Route::post('/detail/{id}/review', 'Frontend\DetailMedicinesController@reviewMedicine');

    Route::get('/contact/sendemail', 'Frontend\HomeController@indexSendEmail')->name('frontend.contact.index');
    Route::post('/contact/sendemail', 'Frontend\HomeController@sendEmail')->name('frontend.sendemail');

    // Comment
    Route::get('/comment/json/getList', 'Frontend\DetailMedicinesController@jsonCommentList');

    // Detail medicine
    Route::get('detail/{id}/{name}', 'Frontend\DetailMedicinesController@index')->name('detail');

    Route::get('/{parent}', 'Frontend\MedicinesListController@showParentCategories')->name('nav');
    Route::get('/{parentLink}/{subLink}', 'Frontend\MedicinesListController@showSubCategory')->name('sub_Nav');
});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Eloquent\User;
use App\Eloquent\Order;
use App\Eloquent\RateMedicine;
use App\Eloquent\RequestMedicine;
use App\Eloquent\Comment;
use App\Helpers\Helper;
use Validator;
use Session;

class UserController extends Controller
{
    protected $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $users = $this->user->orderBy('id', 'desc')->paginate(15);
        $data['users'] = $users;
        $data['permissionOption'] = $this->user->getPermissionOption();

        return view('admin.user.user-list', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissionOption = $this->user->getPermissionOption();

        return view('admin.user.user-add', compact('permissionOption'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email|max:255',
            'display_name' => 'required|max:255',
            'password' => 'required',
            'confirm_password' => 'required|same:password',
            'avatar'    => 'image',
        ]);
       
        $validator->after(function ($validator) {
            $dataRequest = $validator->getData();
            $currentUser = User::where('email', $dataRequest['email'])->first();
            if ($currentUser) {
                $validator->errors()->add('email', __('Sorry, this email already exists!'));
            }
        });

        if ($validator->fails()) {
            return redirect('admin/users/create')
                ->withErrors($validator)
                ->withInput($request->input);
        }

        $user = $this->user;
        $user->fill($request->except(['password', 'avatar']));
        $user->password = bcrypt($request->password);
        
        if ($request->hasFile('avatar')) {
            $nameFile = $request->avatar->hashName();
            $path = $request->file('avatar')->store(User::PATH_AVATAR, 'uploads');
            $user->avatar = $path;
        }

        try {
            $user->save();
            $message = __('Add new user :name successfully!', ['name' => $user->display_name]);
            Helper::addMessageFlashSession(__('Success'), $message, 'success');
        } catch (Exception $e){
            Helper::addMessageFlashSession(__('Error'), $e->getMessage(), 'danger');

            return redirect('admin/users/create')->withInput($request->input);
        }

        return redirect('admin/users');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        if (!$user) return redirect()->route('users.index');

        $permissionOption = $this->user->getPermissionOption();

        $orderCollection = Order::where('user_id', $user->id)->orderBy('id', 'desc')->get();
        $data['orders']['list'] = $orderCollection;
        $data['orders']['pending'] = $orderCollection->where('status', Order::STATUS_PENDING);
        $data['orders']['complete'] = $orderCollection->where('status', Order::STATUS_COMPLETE);
        $data['orders']['cancel'] = $orderCollection->where('status', Order::STATUS_CANCEL);
        $data['orders']['refund'] = $orderCollection->where('status', Order::STATUS_REFUND);
        $data['orders']['options'] = Order::getOptionStatus();

        $data['review']['count'] = RateMedicine::select('id')->where('user_id', $user->id)->get()->count();
        $data['comment']['question'] = Comment::select('id')->getQuestionByUserId($user->id)->get()->count();
        $data['comment']['answer'] = Comment::select('id')->getAnswerByUserId($user->id)->get()->count();
        $data['request']['medicine'] = RequestMedicine::select('id')->where('user_id', $user->id)->get()->count();

        $data['user']['optionGender'] = $this->user->getGenderOption();

        return view('admin.user.user-detail', compact(['user', 'permissionOption', 'data']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $permissionOption = $this->user->getPermissionOption();

        return view('admin.user.user-edit', ['user' => $user, 'permissionOption' => $permissionOption]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validator = Validator::make($request->all(), [
            'display_name' => 'required|max:255',
            'confirm_password' => 'same:password',
            'avatar'    => 'image',
        ]);
       
        if ($validator->fails()) {
            return redirect('admin/users/'. $user->id .'/edit')
                ->withErrors($validator)
                ->withInput($request->input);
        }

        $user->fill($request->except(['password', 'email', 'avatar']));
        if ($request->password){
            $user->password = bcrypt($request->password);
        }

        if ($request->hasFile('avatar')) {
            Helper::deleteFile($user->avatar);

            $nameFile = $request->avatar->hashName();
            $path = $request->file('avatar')->store(User::PATH_AVATAR, 'uploads');
            $user->avatar = $path;
        }

        try {
            $user->save();
            $message = __('Edit user :name successfully!', ['name' => $user->display_name]);
            Helper::addMessageFlashSession(__('Success'), $message, 'success');
        } catch (Exception $e){
            Helper::addMessageFlashSession(__('Error'), $e->getMessage(), 'danger');

            return redirect('admin/users/'. $user->id .'/edit')->withInput($request->input);
        }

        return redirect('admin/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if ($user){
            try {
                $user->delete();
                $message = __('Delete user :name successfully!', ['name' => $user->display_name]);
                Helper::deleteFile($user->avatar);
                Helper::addMessageFlashSession(__('Success'), $message, 'success');
            } catch (Exception $e) {
                Helper::addMessageFlashSession(__('Error'), $e->getMessage(), 'danger');
            }
        }
        
        return redirect()->route('users.index');
    }
}

resources/views/admin/user/user-add.blade.php
@extends('admin.layouts.admin-layout')

@section('pageAdminTitle', __('Add New User'))

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>{{ __('Add New User') }}</h1>
    <ol class="breadcrumb">
        <li><a href="{!! url('admin') !!}"><i class="fa fa-dashboard"></i>{{ __('Home') }}</a></li>
        <li class="active">{{ __('New User') }}</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="col-md-10">
                        <h3 class="box-title">{{ __('New User') }}</h3>
                    </div>
                    <div class="col-md-2 text-right">
                        {!! Form::button(__('Save'), ['type' => 'submit', 'form' => 'add-new-user', 'data-toggle' => 'tooltip', 'class' => 'btn btn-primary', 'data-original-title' => __('Save')]) !!}

                        <a href="{!! url('admin/users') !!}" data-toggle="tooltip" class="btn btn-default" data-original-title="{{ __('Cancel') }}">
                            <i class="fa fa-reply"></i>
                        </a>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    {!! Form::open(['route' => 'users.store', 'id' => 'add-new-user', 'class' => 'form-horizontal', 'method' => 'post', 'files' => 'true']) !!}

                        <div class="form-group">
                            <div class="col-sm-6">
                                {!! Form::label('email', __('Email'), ['class' => 'col-sm-3 control-label']) !!}

                                <div class="col-sm-9">
                                    {!! Form::email('email', '', ['class' => 'form-control', 'placeholder' => __('Email')]) !!}
                                    <span class="text-danger">{!! $errors->first('email') !!}</span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                {!! Form::label('display_name', __('Display Name'), ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-9">
                                    {!! Form::text('display_name', '', ['class' => 'form-control', 'placeholder' => __('Display Name')]) !!}
                                    <span class="text-danger">{!! $errors->first('display_name') !!}</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6">
                                {!! Form::label('phone', __('Phone'), ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-9">
                                    {!! Form::text('phone', '', ['class' => 'form-control', 'placeholder' => __('Phone')]) !!}
                                    <span class="text-danger">{!! $errors->first('phone') !!}</span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                {!! Form::label('address', __('Address'), ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-9">
                                    {!! Form::text('address', '', ['class' => 'form-control', 'placeholder' => __('Address')]) !!}
                                    <span class="text-danger">{!! $errors->first('address') !!}</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6">
                                {!! Form::label('password', __('Password'), ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-9">
                                    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => __('Password')]) !!}
                                    <span class="text-danger">{!! $errors->first('password') !!}</span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                {!! Form::label('confirm_password', __('Confirm Password'), ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-9">
                                    {!! Form::password('confirm_password', ['class' => 'form-control', 'placeholder' => __('Confirm Password')]) !!}
                                    <span class="text-danger">{!! $errors->first('confirm_password') !!}</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6">
                                {!! Form::label('avatar', __('Avatar'), ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-9">
                                    {!! Form::file('avatar', ['class' => 'form-control']) !!}
                                    <span class="text-danger">{!! $errors->first('avatar') !!}</span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                {!! Form::label('permission', __('Permission'), ['class' => 'col-sm-3 control-label']) !!}
                                <div class="col-sm-9">
                                    {!! Form::select('permission', $permissionOption, null, ['class' => 'form-control']) !!}
                                    <span class="text-danger">{!! $errors->first('permission') !!}</span>
                                </div>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@endsection

resources/views/admin/user/user-list.blade.php
@extends('admin.layouts.admin-layout')

@section('pageAdminTitle', __('List Users'))

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ __('User') }}
        <small>{{ __('List') }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{!! url('admin') !!}"><i class="fa fa-dashboard"></i>{{ __('Home') }}</a></li>
        <li class="active">{{ __('List Users') }}</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="col-md-10">
                        <h3 class="box-title">{{ __('List Users') }}</h3>
                    </div>
                    <div class="col-md-1 text-right">
                        <a href="{!! url('admin/users/create') !!}" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="{{ __('Add New') }}"><i class="fa fa-plus"></i></a>
                    </div>
                    <div class="col-md-1">
                        <a href="" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="{{ __('Rebuild') }}"><i class="fa fa-refresh"></i></a>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <table id="user_list_table" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('ID #') }}</th>
                            <th>{{ __('E-Mail Address') }}</th>
                            <th>{{ __('Display name') }}</th>
                            <th>{{ __('Permission') }}</th>
                            <th>{{ __('Action') }}</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php $users = $data['users'] ?>

                        @foreach($users as $user)
                            <tr>
                                <td>
                                    <span>{{ $user->id }}</span>
                                </td>
                                <td>
                                    <span>{{ $user->email }}</span>
                                </td>
                                <td>
                                    <span>{{ $user->display_name }}</span>
                                </td>
                                <td>
                                    <span>{{ $data['permissionOption'][$user->permission] }}</span>
                                </td>
                                <td>
                                    {!! Form::open(['route' =>['users.destroy', $user->id], 'method' => 'DELETE']) !!}
                                        <span class="text-right">
                                            <a href="{{ route('users.show', [$user->id]) }}" data-toggle="tooltip" class="btn btn-primary" data-original-title="{{ __('View Detail') }}">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                        </span>
                                        <span class="text-right">
                                            <a href="{{ route('users.edit', [$user->id]) }}" data-toggle="tooltip" class="btn btn-primary" data-original-title="{{ __('Edit') }}">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                        </span>
                                        @if ($user->id != Auth::user()->id)
                                            <a href="javascript:void(0)" data-text="{{ __('Do you want to delete?') }}" data-toggle="tooltip" class="btn btn-danger" onclick="confirmButtonBeforeSubmit(this)"data-original-title="{{ __('Delete') }}">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        @endif
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@endsection

@section('javascript')
<script lang="javascript">
    $(function() {
        $("#user_list_table").DataTable({
            "order": [[ 0, "desc" ]]
        });
    });
</script>
@endsection